

DROP TABLE IF EXISTS ORDER_ITEMS;
CREATE TABLE `ORDER_ITEMS` (
	`ID`	CHAR(36)	NOT NULL,
	`ORDERS_ID`	CHAR(36)	NOT NULL,
	`PRODUCTS_ID`	CHAR(36)	NOT NULL,
	`QUANTITY`	INT	NOT NULL	DEFAULT 1,
	`PRICE`	INT	NOT NULL	DEFAULT 0,
	`AMOUNT`	INT	NULL,
	`CREATED_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);
------------------------------------------------------------------------------


TRUNCATE ORDER_ITEMS;
INSERT INTO ORDER_ITEMS (ID, ORDERS_ID, PRODUCTS_ID, QUANTITY, PRICE, AMOUNT) 
VALUES ( #{id}, #{ordersId}, #{productsId}, #{quantity}, #{price}, #{amount} )

;


SELECT *
FROM user
WHERE id = 'u1b2c3d4-e5f6-7890-abcd-ef1234567890';