-- Active: 1717838232505@@127.0.0.1@3306@mypet
DROP TABLE IF EXISTS `pet`;

CREATE TABLE `pet` (
	`no`	INT	NOT NULL,
	`file_no`	INT	NOT NULL,
	`name`	VARCHAR(50)	NOT NULL,
	`age`	INT	NOT NULL,
	`petgender`	INT	NOT NULL,
	`character`	VARCHAR(100)	NULL,
	`type`	VARCHAR(50)	NULL,
	`reg_date`	TIMESTAMP	NULL	DEFAULT CURRENT_TIMESTAMP,
	`upd_date`	TIMESTAMP	NULL	DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS `reserve`;

CREATE TABLE `reserve` (
	`no`	INT	NOT NULL,
	`user_id`	VARCHAR(100)	NOT NULL,
	`trainer_no`	INT	NOT NULL,
	`request`	VARCHAR(400)	NULL,
	`condition`	VARCHAR(50)	NOT NULL,
	`TITLE`	VARCHAR(100)	NOT NULL,
	`TOTAL_QUANTITIY`	INT	NOT NULL	DEFAULT 1,
	`TOTAL_COUNT`	INT	NOT NULL	DEFAULT 1,
	`TOTAL_PRICE`	INT	NOT NULL	DEFAULT 0,
	`STATUS`	ENUM('PENDING','PAID','REFUND')	NULL	DEFAULT'PENDING', -- 결제대기,결제완료,환불
	`reg_date`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`upd_date`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS `reservlist`;

CREATE TABLE `reservlist` (
	`no`	INT	NOT NULL,
	`reserv_no`	INT	NOT NULL,
	`train_no`	INT	NOT NULL,
	`PRICE`	INT	NOT NULL	DEFAULT 0,
	`AMOUNT`	INT	NULL,
	`order_day`	TIMESTAMP	NOT NULL,
	`reg_date22`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`upd_date22`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS `orders`;

INSERT INTO `trainer` (
    `no`, `user_id`, `name`, `gender`, `birth`, `mail`, `phone`, `address`, `reg_date`, `upd_date`, `content`
) VALUES
    (1, 'user', 'Alice', 'female', '1990-01-01', 'alice@example.com', '123-456-7890', '123 Wonderland Ave', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Alice is an experienced trainer specializing in various fitness programs.'),
    (2, 'admin', 'Bob', 'male', '1985-05-12', 'bob@example.com', '234-567-8901', '456 Elm Street', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Bob is a certified personal trainer with a focus on strength training.'),
    (3, 'dddd', 'Charlie', 'male', '1992-09-23', 'charlie@example.com', '345-678-9012', '789 Maple Road', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Charlie has extensive experience in endurance training and nutrition.'),
    (4, 'aaaa', 'Diana', 'female', '1988-12-11', 'diana@example.com', '456-789-0123', '101 Birch Blvd', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Diana specializes in yoga and mindfulness training.'),
    (5, 'ssss', 'Eve', 'female', '1995-04-05', 'eve@example.com', '567-890-1234', '202 Pine Lane', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Eve is a fitness enthusiast with a passion for HIIT and cardio workouts.');

DROP TABLE QnA;
CREATE TABLE `QnA` (
	`qna_no`	INT	NOT NULL,
	`qna_title`	VARCHAR(100)	NOT NULL,
	`qna_writer`	VARCHAR(100)	NOT NULL,
	`qna_content`	VARCHAR(100)	NULL,
	`board_type`	VARCHAR(100)	NOT NULL,
	`reg_date`	TIMESTAMP	NOT NULL,
	`upd_date`	TIMESTAMP	NOT NULL
);

DROP TABLE QnA;

INSERT INTO `qna` (`qna_title`, `qna_writer`, `qna_content`, `board_type`, `reg_date`, `upd_date`) VALUES
('Question about membership', 'user1', 'How do I upgrade my membership?', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Technical issue with login', 'user2', 'I cannot log in to my account.', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Feedback on the new feature', 'user3', 'The new feature is very helpful.', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Payment process question', 'user4', 'How can I change my payment method?', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('General inquiry about services', 'user5', 'What services do you offer?', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);


CREATE TABLE `orders` (
	`order_no`	INT	NOT NULL,
	`date_no`	INT	NOT NULL,
	`STATUS`	ENUM('PENDING','PAID','REFUND')	NOT NULL	DEFAULT'PENDING', -- 결제대기,결제완료,환불,
	`PAYMENT_METHOD`	VARCHAR(255)	NULL,
	`pay_check`	BOOLEAN	NULL,
	`reg_date2`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`upd_date2`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`pay_date`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`price`	INT	NOT NULL
);

DROP TABLE IF EXISTS `img_file`;

CREATE TABLE `img_file` (
	`no`	INT	NOT NULL,
	`parent_no`	INT	NOT NULL,
	`parent_table`	VARCHAR(100)	NOT NULL,
	`file_name`	VARCHAR(100)	NOT NULL,
	`file_path`	VARCHAR(100)	NOT NULL,
	`file_size`	LONG	NULL,
	`file_code`	VARCHAR(50)	NULL,
	`reg_date`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`upd_date`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS `reply`;

CREATE TABLE `reply` (
	`no`	INT	NOT NULL,
	`board_no2`	INT	NOT NULL,
	`user_id`	VARCHAR(100)	NOT NULL,
	`parent_no`	VARCHAR(100)	NULL,
	`writer`	VARCHAR(100)	NULL,
	`content`	VARCHAR(1000)	NULL,
	`upd_date`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`reg_date`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS `notice`;

CREATE TABLE `notice` (
	`notice_no`	INT	NOT NULL,	-- DEFAULT AUTO_INCREMENT,
	`notice_content`	VARCHAR(1000)	NOT NULL,
	`writer`	VARCHAR(50)	NOT NULL,
	`reg_date`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`upd_date`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS `board`;

CREATE TABLE `board` (
	`no`	INT	NOT NULL,
	`user_id`	VARCHAR(100)	NOT NULL,
	`title`	VARCHAR(100)	NOT NULL,
	`writer`	VARCHAR(100)	NULL,
	`content`	VARCHAR(1000)	NULL,
	`file_no`	VARCHAR(100)	NULL,
	`board_type`	INT	NULL	DEFAULT 1, -- 1.일반 2관리자3.공지사항,
	`reg_date`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`upd_date`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS `review`;

CREATE TABLE `review` (
	`review_no`	INT	NOT NULL,
	`user_id`	VARCHAR(100)	NOT NULL,
	`rating`	INT	NULL,
	`content`	VARCHAR(1000)	NULL,
	`reg_date`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`upd_date`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS `user_auth`;

CREATE TABLE `user_auth` (
	`auth_no`	INT	NOT NULL,
	`user_id`	VARCHAR(100)	NOT NULL,
	`auth`	VARCHAR(40)	NULL
);

DROP TABLE IF EXISTS `schedule`;

CREATE TABLE `schedule` (
	`no`	INT	NOT NULL,
	`user_id`	VARCHAR(100)	NOT NULL,
	`trainer_no`	INT	NOT NULL,
	`title`	VARCHAR(50)	NULL	DEFAULT 'holiday', -- 휴무,
	`content`	TEXT	NULL,
	`schedule_date`	TIMESTAMP	NULL,
	`reg_date`	TIMESTAMP	NULL	DEFAULT CURRENT_TIMESTAMP,
	`upd_date`	TIMESTAMP	NULL	DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS `career`;
CREATE TABLE career (
    no INT NOT NULL AUTO_INCREMENT,
    user_id VARCHAR(100)	NOT NULL,
    trainer_no INT NOT NULL,
    name VARCHAR(255) NOT NULL,
    reg_date DATETIME NOT NULL,
    upd_date DATETIME NOT NULL,
    PRIMARY KEY (no)
);


DROP TABLE IF EXISTS `certificate`;
DROP TABLE IF EXISTS `career`;

DROP TABLE IF EXISTS `trainer`;

CREATE TABLE `trainer` (
	`no`	INT	NOT NULL,
	`user_id`	VARCHAR(100)	NOT NULL,
	`name`	VARCHAR(50)	NOT NULL,
	`gender`	VARCHAR(50)	NOT NULL,
	`birth`	VARCHAR(50)	NOT NULL,
	`address`	VARCHAR(150)	NULL,
	`content`	TEXT	NULL,
	`phone`	INT	NULL,
	`mail`	VARCHAR(50)	NULL,
	`reg_date`	TIMESTAMP	NULL	DEFAULT CURRENT_TIMESTAMP,
	`upd_date`	TIMESTAMP	NULL	DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS `users`;

CREATE TABLE `users` (
	`user_id`	VARCHAR(100)	NOT NULL,
	`user_no`	INT	NOT NULL,
	`pet_no`	INT	NOT NULL,
	`no`	INT	NOT NULL,
	`name`	VARCHAR(50)	NOT NULL,
	`password`	VARCHAR(100)	NOT NULL,
	`birth`	VARCHAR(50)	NOT NULL,
	`address`	VARCHAR(150)	NULL,
	`mail`	VARCHAR(50)	NULL,
	`phone`	VARCHAR(50)	NULL,
	`gender`	VARCHAR(50)	NULL,
	`enable`	INT	NULL,
	`role`	INT	NULL,
	`reg_date`	TIMESTAMP	NULL	DEFAULT CURRENT_TIMESTAMP,
	`upd_date`	TIMESTAMP	NULL	DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS `PRODUCTS`;

CREATE TABLE `PRODUCTS` (
	`no`	INT	NOT NULL,
	`no2`	INT	NOT NULL,
	`NAME`	VARCHAR(100)	NOT NULL,
	`CAREGORY`	VARCHAR(100)	NULL,
	`DESCRIPTION`	VARCHAR(100)	NULL,
	`PRICE`	INT	NOT NULL,
	`reg_date22`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`upd_date22`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS `CATEGORIES`;

CREATE TABLE `CATEGORIES` (
	`no`	INT	NOT NULL,
	`CODE`	VARCHAR(100)	NOT NULL,
	`NAME`	VARCHAR(100)	NOT NULL,
	`SEQ`	INT	NOT NULL	DEFAULT 0,
	`reg_date22`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`upd_date22`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS `CANCELLATIONS`;

CREATE TABLE `CANCELLATIONS` (
	`NO`	INT	NOT NULL,
	`date_no`	INT	NOT NULL,
	`STATUS`	ENUM('PENDING','PAID','REFUND')	NOT NULL	DEFAULT 'PENDING', -- 결제대기,결제완료,환불,
	`PAYMENT_METHOD`	VARCHAR(255)	NULL,
	`pay_check`	BOOLEAN	NULL,
	`pay_date`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`type`	ENUM('PENDING','PAID','REFUND')	NULL	DEFAULT 'REFUND',
	`REASON`	TEXT	NULL,
	`REFUNDED_AMOUNT`	INT	NOT NULL,
	`IS_CONFIRMED`	TINYINT(1)	NOT NULL	DEFAULT 0,
	`IS_REFUND`	TINYINT(1)	NOT NULL,
	`ACCOUNT_NUMBER`	VARCHAR(100)	NULL,
	`BANK_NAME`	VARCHAR(100)	NULL,
	`DEPOSITOR`	VARCHAR(100)	NULL,
	`CANCELED_AT`	TIMESTAMP	NULL,
	`COMPLETED_AT`	TIMESTAMP	NULL,
	`reg_date`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`upd_date`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS `CARTS`;

CREATE TABLE `CARTS` (
	`no`	INT	NOT NULL,
	`user_id`	VARCHAR(100)	NOT NULL,
	`no2`	INT	NOT NULL,
	`ORDER_DAY`	TIMESTAMP	NOT NULL,
	`reg_date22`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`upd_date22`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE `pet` ADD CONSTRAINT `PK_PET` PRIMARY KEY (
	`no`
);

ALTER TABLE `reserve` ADD CONSTRAINT `PK_RESERVE` PRIMARY KEY (
	`no`
);

ALTER TABLE `reservlist` ADD CONSTRAINT `PK_RESERVLIST` PRIMARY KEY (
	`no`
);

ALTER TABLE `orders` ADD CONSTRAINT `PK_ORDERS` PRIMARY KEY (
	`order_no`
);

ALTER TABLE `img_file` ADD CONSTRAINT `PK_IMG_FILE` PRIMARY KEY (
	`no`
);

ALTER TABLE `reply` ADD CONSTRAINT `PK_REPLY` PRIMARY KEY (
	`no`
);

ALTER TABLE `notice` ADD CONSTRAINT `PK_NOTICE` PRIMARY KEY (
	`notice_no`
);

ALTER TABLE `board` ADD CONSTRAINT `PK_BOARD` PRIMARY KEY (
	`no`
);

ALTER TABLE `review` ADD CONSTRAINT `PK_REVIEW` PRIMARY KEY (
	`review_no`
);

ALTER TABLE `user_auth` ADD CONSTRAINT `PK_USER_AUTH` PRIMARY KEY (
	`auth_no`
);

ALTER TABLE `schedule` ADD CONSTRAINT `PK_SCHEDULE` PRIMARY KEY (
	`no`
);

ALTER TABLE `career` ADD CONSTRAINT `PK_CAREER` PRIMARY KEY (
	`no`
);

ALTER TABLE `certificate` ADD CONSTRAINT `PK_CERTIFICATE` PRIMARY KEY (
	`no`
);

ALTER TABLE `trainer` ADD CONSTRAINT `PK_TRAINER` PRIMARY KEY (
	`no`
);

ALTER TABLE `users` ADD CONSTRAINT `PK_USERS` PRIMARY KEY (
	`user_id`
);

ALTER TABLE `PRODUCTS` ADD CONSTRAINT `PK_PRODUCTS` PRIMARY KEY (
	`no`
);

ALTER TABLE `CATEGORIES` ADD CONSTRAINT `PK_CATEGORIES` PRIMARY KEY (
	`no`
);

ALTER TABLE `CANCELLATIONS` ADD CONSTRAINT `PK_CANCELLATIONS` PRIMARY KEY (
	`NO`
);

ALTER TABLE `CARTS` ADD CONSTRAINT `PK_CARTS` PRIMARY KEY (
	`no`
);