-- Active: 1713528331467@@127.0.0.1@3306@mypet

------------------------------------------------------------------------------
-- 이미지파일 C:\upload\no-image.png 로 이미지 임시파일만들어주세요
DROP TABLE IF EXISTS products;
CREATE TABLE `PRODUCTS` (
	`ID`	CHAR(255)	NOT NULL PRIMARY KEY,
    `TRAINER_NO` INT NOT NULL,                          -- 훈련사 번호
	`NAME`	VARCHAR(100)	NOT NULL,                   -- 훈련 교육 제목
	`DESCRIPTION`	VARCHAR(200)	NULL,               -- 훈련 간단 설명
	`CONTENT`	TEXT	NULL,                           -- 훈련 내용
	`PRICE`	INT	NOT NULL,                               -- 가격
	`CREATED_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);
------------------------------------------------------------------------------


DROP TABLE IF EXISTS CATEGORIES;
CREATE TABLE `CATEGORIES` (
	`ID`	CHAR(36)	NOT NULL PRIMARY KEY,
	`CODE`	VARCHAR(100)	NOT NULL UNIQUE,
	`NAME`	VARCHAR(100)	NOT NULL,
	`SEQ`	INT	NOT NULL DEFAULT 1,
	`CREATED_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);
------------------------------------------------------------------------------


DROP TABLE IF EXISTS CARTS;
CREATE TABLE `CARTS` (
	`ID`	CHAR(36)	NOT NULL PRIMARY KEY,
	`PRODUCTS_ID`	CHAR(36)	NOT NULL,
	`USER_ID`	CHAR(36)	NOT NULL,
	`AMOUNT`	INT	NOT NULL	DEFAULT 1,
	`CREATED_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);
------------------------------------------------------------------------------



DROP TABLE IF EXISTS ORDERS;

-- ORDERS 테이블 생성
CREATE TABLE `orders` (
	`DATE_NO` INT PRIMARY KEY AUTO_INCREMENT,            -- 예약 번호
	`ID` CHAR(36) NOT NULL,                              -- 예약 id
	`USER_ID` VARCHAR(100) NOT NULL,                     -- 회원 id
	`trainer_no` INT NOT NULL,                           -- 훈련사id
	`MEMO` VARCHAR(255) NULL,                            -- 요청사항
	`resDate` TIMESTAMP NOT NULL,                        -- 예약날짜
	`TITLE` VARCHAR(255) NULL,                           -- 예약제목
	`TOTAL_QUANTITY` INT NOT NULL DEFAULT 1,             -- 예약일수
	`TOTAL_COUNT` INT NOT NULL DEFAULT 1,
	`TOTAL_PRICE` INT NOT NULL DEFAULT 0,                -- 예약금액
	`STATUS` VARCHAR(20) NOT NULL DEFAULT 'pending' COMMENT '결제대기, 결제완료, 승인중,훈련완료,예약취소',
	`ORDERED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,  -- 결제일
	`CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,  
	`UPDATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


------------------------------------------------------------------------------


DROP TABLE IF EXISTS ORDER_ITEMS;
CREATE TABLE `ORDER_ITEMS` (
	`ID`	CHAR(36)	NOT NULL PRIMARY KEY,
	`DATE_NO` INT NOT NULL,            -- 예약 번호
	`PRODUCTS_ID`	CHAR(36)	NOT NULL,
	`PRICE`	INT	NOT NULL	DEFAULT 0,
	`AMOUNT`	INT	NULL,
	`resDate` TIMESTAMP NOT NULL,                        -- 예약날짜
	`CREATED_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);
------------------------------------------------------------------------------


DROP TABLE IF EXISTS PAYMENTS;
CREATE TABLE `PAYMENTS` (
	`ID`	CHAR(36)	NOT NULL PRIMARY KEY,
	`DATE_NO` INT NOT NULL,            -- 예약 번호
	`PAYMENT_METHOD`	VARCHAR(255)	NULL,
	`STATUS`	VARCHAR(255)	NULL,
	`PAID_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`CREATED_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);

------------------------------------------------------------------------------


DROP TABLE IF EXISTS CANCELLATIONS;
CREATE TABLE `CANCELLATIONS` (
	`ID`	CHAR(36)	NOT NULL PRIMARY KEY,
	`DATE_NO` INT NOT NULL,            -- 예약 번호
	`TYPE`	ENUM('CANCEL','EXCHANGE')	NOT NULL	DEFAULT 'CANCEL'	COMMENT '주문취소,환불',
	`STATUS`	ENUM('PENDING','complete')	NULL	DEFAULT 'PENDING'	COMMENT '취소요청(대기), 처리완료',
	`REASON`	TEXT	NULL,
	`REFUNDED_AMOUNT`	INT	NOT NULL	DEFAULT 0,
	`IS_CONFIRMED`	TINYINT(1)	NOT NULL	DEFAULT 0	COMMENT '0: 미승인, 1: 승인',
	`IS_REFUND`	TINYINT(1)	NOT NULL	DEFAULT 0	COMMENT '0: 대기, 1: 처리완료',
	`ACCOUNT_NUMBER`	VARCHAR(100)	NULL,
	`BANK_NAME`	VARCHAR(100)	NULL,
	`DEPOSITOR`	VARCHAR(100)	NULL,
	`CANCELED_AT`	TIMESTAMP	NULL,
	`COMPLETED_AT`	TIMESTAMP	NULL,
	`CREATED_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);
------------------------------------------------------------------------------


DROP TABLE IF EXISTS FILES;
CREATE TABLE `FILES` (
	`ID`	CHAR(36)	NOT NULL PRIMARY KEY,
	`PARENT_TABLE`	VARCHAR(100)	NOT NULL,
	`PARENT_ID`	VARCHAR(100)	NOT NULL,
	`NAME`	TEXT	NOT NULL,
	`ORIGIN_NAME`	TEXT	NOT NULL,
	`PATH`	TEXT	NOT NULL,
	`SIZE`	BIGINT	NOT NULL	DEFAULT 0,
	`IS_MAIN`	BOOLEAN	NOT NULL	DEFAULT FALSE,
	`SEQ`	INT	NOT NULL	DEFAULT 0,
	`CREATED_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE files MODIFY id VARCHAR(36);



------------------------------------------------------------------------------
DROP TABLE IF EXISTS `PAYMENTS`;

CREATE TABLE `PAYMENTS` (
	`ID`	CHAR(36)	NOT NULL PRIMARY KEY,               -- 결제번호
	`date_no`	CHAR(36)	NOT NULL,                       -- 예약번호
	`PAYMENT_METHOD`	VARCHAR(255)	NULL,               -- 결제방식
	`STATUS`	VARCHAR(255)	NULL,                       -- 결제상태
	`pay_date`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,  -- 결제일자
	`CREATED_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);




SELECT * FROM address;

DROP TABLE IF EXISTS CATEGORIES;
CREATE TABLE `CATEGORIES` (
    `ID` CHAR(36) PRIMARY KEY, -- UUID 형식의 고유 ID
    `CODE` VARCHAR(50) NOT NULL, -- 카테고리 코드
    `NAME` VARCHAR(100) NOT NULL, -- 카테고리 이름
    `SEQ` INT NOT NULL, -- 순서
    `CREATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- 생성일
    `UPDATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP -- 수정일
);

-- Active: 1713528331467@@127.0.0.1@3306@mypet
INSERT INTO `CATEGORIES` (`ID`, `CODE`, `NAME`, `SEQ`, `CREATED_AT`, `UPDATED_AT`) VALUES
('1a2b3c4d-5678-90ab-cdef-1234567890ab', '1', '훈련', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('2b3c4d5e-6789-01ab-cdef-2345678901bc', '2', '돌봄', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

--------------------------------------------------------------------------------------------------
TRUNCATE products;
-- Inserting sample data

INSERT INTO PRODUCTS (ID, TRAINER_NO, NAME, DESCRIPTION, CONTENT, PRICE, CREATED_AT, UPDATED_AT) VALUES
('001', 1, '이태원', '서울시 강남구 테헤란로 123', '트레이너 경력 10년', 50, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('002', 2, '강형욱', '서울시 강남구 테헤란로 123', '트레이너 경력 20년', 75, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
commit;
--------------------------------------------------------------------------------------------------

TRUNCATE orders;
TRUNCATE order_items;
INSERT INTO orders (ID, USER_ID, trainer_no, MEMO, resDate, TITLE, TOTAL_QUANTITY, TOTAL_COUNT, TOTAL_PRICE, STATUS, ORDERED_AT)
VALUES 
( 1,'user123', 1, '요청사항입니다.', '2024-06-10 10:00:00', '예약 제목 1', 3, 1, 50000, 'pending', '2024-06-08 10:00:00'),
( 2,'user456', 2, NULL, '2024-06-11 15:00:00', '예약 제목 2', 2, 1, 40000, 'pending', '2024-06-08 11:00:00');


TRUNCATE files;
INSERT INTO `FILES` (`ID`, `PARENT_TABLE`, `PARENT_ID`, `NAME`, `ORIGIN_NAME`, `PATH`, `SIZE`, `IS_MAIN`, `SEQ`, `CREATED_AT`, `UPDATED_AT`) VALUES
('a1b2c3d4-5678-90ab-cdef-111111111111', 'products', '5e6f7g8h-9012-34ab-cdef-5678901234ef', 'TOP1', 'TOP1', 'C:\\upload\\TOP1.jpg', 1000, TRUE, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('b2c3d4e5-6789-01ab-cdef-222222222222', 'products', '6f7g8h9i-0123-45ab-cdef-6789012345fg', 'TOP2', 'TOP2', 'C:\\upload\\TOP2.jpg', 2000, TRUE, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);



