-- Active: 1713528331467@@127.0.0.1@3306@mypet


DROP TABLE IF EXISTS USER;
CREATE TABLE `USER` (
	`ID`	CHAR(36)	NOT NULL PRIMARY KEY,
	`USERNAME`	VARCHAR(100)	NOT NULL UNIQUE,
	`PASSWORD`	VARCHAR(100)	NOT NULL,
	`NAME`	VARCHAR(100)	NOT NULL,
	`PHONE`	VARCHAR(20)	NOT NULL,
	`CREATED_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`ENABLED`	INT	NOT NULL	DEFAULT 1
);
------------------------------------------------------------------------------

DROP TABLE IF EXISTS USER_AUTH;
CREATE TABLE `USER_AUTH` (
	`ID`	CHAR(36)	NOT NULL PRIMARY KEY,
	`USERNAME`	VARCHAR(100)	NOT NULL,
	`AUTH`	VARCHAR(100)	NOT NULL
);
------------------------------------------------------------------------------

DROP TABLE IF EXISTS products;
CREATE TABLE `PRODUCTS` (
	`ID`	CHAR(36)	NOT NULL PRIMARY KEY,
	`NAME`	VARCHAR(100)	NOT NULL,
	`CATEGORY`	VARCHAR(100)	NULL,
	`DESCRIPTION`	VARCHAR(200)	NULL,
	`CONTENT`	TEXT	NULL,
	`PRICE`	INT	NOT NULL,
	`STOCK`	INT	NULL	DEFAULT 0,
	`CREATED_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);
------------------------------------------------------------------------------


DROP TABLE IF EXISTS CATEGORIES;
CREATE TABLE `CATEGORIES` (
	`ID`	CHAR(36)	NOT NULL PRIMARY KEY,
	`CODE`	VARCHAR(100)	NOT NULL UNIQUE,
	`NAME`	VARCHAR(100)	NOT NULL,
	`SEQ`	INT	NOT NULL DEFAULT 1,
	`CREATED_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);
------------------------------------------------------------------------------


DROP TABLE IF EXISTS CARTS;
CREATE TABLE `CARTS` (
	`ID`	CHAR(36)	NOT NULL PRIMARY KEY,
	`PRODUCTS_ID`	CHAR(36)	NOT NULL,
	`USER_ID`	CHAR(36)	NOT NULL,
	`AMOUNT`	INT	NOT NULL	DEFAULT 1,
	`CREATED_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);
------------------------------------------------------------------------------


DROP TABLE IF EXISTS ORDERS;
CREATE TABLE `ORDERS` (
	`ID`	CHAR(36)	NOT NULL PRIMARY KEY,
	`USER_ID`	CHAR(36)	NOT NULL,
	`TITLE`	VARCHAR(255)	NULL,
	`TOTAL_QUANTITY`	INT	NOT NULL	DEFAULT 1,
	`TOTAL_COUNT`	INT	NOT NULL	DEFAULT 1,
	`TOTAL_PRICE`	INT	NOT NULL	DEFAULT 0,
	`STATUS`	ENUM('PENDING','PAID','SHIPPING','DELIVERED','CANCELLED')	NOT NULL	DEFAULT 'PENDING'	COMMENT '결제대기, 결제완료, 배송중,배송완료,주문취소',
	`ORDERED_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`CREATED_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);
------------------------------------------------------------------------------


DROP TABLE IF EXISTS ORDER_ITEMS;
CREATE TABLE `ORDER_ITEMS` (
	`ID`	CHAR(36)	NOT NULL PRIMARY KEY,
	`ORDERS_ID`	CHAR(36)	NOT NULL,
	`PRODUCTS_ID`	CHAR(36)	NOT NULL,
	`QUANTITY`	INT	NOT NULL	DEFAULT 1,
	`PRICE`	INT	NOT NULL	DEFAULT 0,
	`AMOUNT`	INT	NULL,
	`CREATED_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);
------------------------------------------------------------------------------


DROP TABLE IF EXISTS PAYMENTS;
CREATE TABLE `PAYMENTS` (
	`ID`	CHAR(36)	NOT NULL PRIMARY KEY,
	`ORDERS_ID`	CHAR(36)	NOT NULL,
	`PAYMENT_METHOD`	VARCHAR(255)	NULL,
	`STATUS`	VARCHAR(255)	NULL,
	`PAID_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`CREATED_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);

------------------------------------------------------------------------------


DROP TABLE IF EXISTS CANCELLATIONS;
CREATE TABLE `CANCELLATIONS` (
	`ID`	CHAR(36)	NOT NULL PRIMARY KEY,
	`ORDERS_ID`	CHAR(36)	NOT NULL,
	`TYPE`	ENUM('CANCEL','RETURN','EXCHANGE')	NOT NULL	DEFAULT 'CANCEL'	COMMENT '주문취소,반품,교환',
	`STATUS`	ENUM('PENDING','complete')	NULL	DEFAULT 'PENDING'	COMMENT '취소요청(대기), 처리완료',
	`REASON`	TEXT	NULL,
	`REFUNDED_AMOUNT`	INT	NOT NULL	DEFAULT 0,
	`IS_CONFIRMED`	TINYINT(1)	NOT NULL	DEFAULT 0	COMMENT '0: 미승인, 1: 승인',
	`IS_REFUND`	TINYINT(1)	NOT NULL	DEFAULT 0	COMMENT '0: 대기, 1: 처리완료',
	`ACCOUNT_NUMBER`	VARCHAR(100)	NULL,
	`BANK_NAME`	VARCHAR(100)	NULL,
	`DEPOSITOR`	VARCHAR(100)	NULL,
	`CANCELED_AT`	TIMESTAMP	NULL,
	`COMPLETED_AT`	TIMESTAMP	NULL,
	`CREATED_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);
------------------------------------------------------------------------------


DROP TABLE IF EXISTS FILES;
CREATE TABLE `FILES` (
	`ID`	CHAR(36)	NOT NULL PRIMARY KEY,
	`PARENT_TABLE`	VARCHAR(100)	NOT NULL,
	`PARENT_ID`	VARCHAR(100)	NOT NULL,
	`NAME`	TEXT	NOT NULL,
	`ORIGIN_NAME`	TEXT	NOT NULL,
	`PATH`	TEXT	NOT NULL,
	`SIZE`	BIGINT	NOT NULL	DEFAULT 0,
	`IS_MAIN`	BOOLEAN	NOT NULL	DEFAULT FALSE,
	`SEQ`	INT	NOT NULL	DEFAULT 0,
	`CREATED_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);
------------------------------------------------------------------------------

DROP TABLE IF EXISTS ADDRESS;
CREATE TABLE `ADDRESS` (
	`ID`	CHAR(36)	NOT NULL PRIMARY KEY,
	`USER_ID`	CHAR(36)	NOT NULL,
	`TITLE`	VARCHAR(100)	NULL	COMMENT '집,회사,사무실',
	`RECIPIENT`	VARCHAR(100)	NULL,
	`ADDRESS`	TEXT	NULL,
	`ADDRESS_DETAIL`	TEXT	NULL,
	`PHONE`	VARCHAR(100)	NULL,
	`REQUEST`	TEXT	NULL	COMMENT '문앞,부재시문앞,경비실,택배함,기타',
	`IS_DEFAULT`	TINYINT(1)	NOT NULL	DEFAULT 0	COMMENT '1: 기본배송지, 0: 기타',
	`ACCESS_NO`	VARCHAR(100)	NULL	COMMENT '공동현관 출입번호',
	`CREATED_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);


------------------------------------------------------------------------------
DROP TABLE IF EXISTS `SHIPMENTS`;

CREATE TABLE `SHIPMENTS` (
	`ID`	CHAR(36)	NOT NULL,
	`ORDERS_ID`	CHAR(36)	NOT NULL,
	`ADDRESS_ID`	CHAR(36)	NOT NULL,
	`TRACKING_NO`	VARCHAR(255)	NULL,
	`SHIP_COMPANY`	VARCHAR(255)	NULL,
	`STATUS`	ENUM('PENDING', 'START', 'SHIPPING', 'DELIVERED', 'CANCELLED')	NULL	COMMENT '배송준비중, 배송시작, 배송중, 배송완료, 주문취소',
	`CREATED_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);


------------------------------------------------------------------------------
DROP TABLE IF EXISTS `PAYMENTS`;

CREATE TABLE `PAYMENTS` (
	`ID`	CHAR(36)	NOT NULL PRIMARY KEY,
	`ORDERS_ID`	CHAR(36)	NOT NULL,
	`PAYMENT_METHOD`	VARCHAR(255)	NULL,
	`STATUS`	VARCHAR(255)	NULL,
	`PAID_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`CREATED_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);

