
ALTER TABLE `USER` ADD CONSTRAINT `PK_USER` PRIMARY KEY (
	`ID`
);

ALTER TABLE `USER_AUTH` ADD CONSTRAINT `PK_USER_AUTH` PRIMARY KEY (
	`ID`
);

ALTER TABLE `PRODUCTS` ADD CONSTRAINT `PK_PRODUCTS` PRIMARY KEY (
	`ID`
);

ALTER TABLE `BASIC` ADD CONSTRAINT `PK_BASIC` PRIMARY KEY (
	`ID`
);

ALTER TABLE `CARTS` ADD CONSTRAINT `PK_CARTS` PRIMARY KEY (
	`ID`
);

ALTER TABLE `ORDERS` ADD CONSTRAINT `PK_ORDERS` PRIMARY KEY (
	`ID`
);

ALTER TABLE `ORDER_ITEMS` ADD CONSTRAINT `PK_ORDER_ITEMS` PRIMARY KEY (
	`ID`
);

ALTER TABLE `PAYMENTS` ADD CONSTRAINT `PK_PAYMENTS` PRIMARY KEY (
	`ID`
);

ALTER TABLE `CANCELLATIONS` ADD CONSTRAINT `PK_CANCELLATIONS` PRIMARY KEY (
	`ID`
);

