

DROP TABLE IF EXISTS ORDER_ITEMS;
CREATE TABLE `ORDER_ITEMS` (
	`ID`  INT      NOT NULL   AUTO_INCREMENT PRIMARY KEY,
	`trainer_no`   INT      NOT NULL,
	`ORDERS_ID`	CHAR(36)	NOT NULL,
	`PRODUCTS_ID`	CHAR(36)	NOT NULL,
	`QUANTITY`	INT	NOT NULL	DEFAULT 1,
	`PRICE`	INT	NOT NULL	DEFAULT 0,
	`AMOUNT`	INT	NULL,
	`CREATED_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);
------------------------------------------------------------------------------

INSERT INTO `ORDER_ITEMS` (`ID`,`trainer_no`, `ORDERS_ID`, `PRODUCTS_ID`, `QUANTITY`, `PRICE`, `AMOUNT`, `CREATED_AT`, `UPDATED_AT`) VALUES
(1, 1, 'order_001', 'product_001', 2, 5000, 10000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2,2, 'order_002', 'product_002', 1, 15000, 15000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,3, 'order_003', 'product_003', 3, 7000, 21000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4,4, 'order_004', 'product_004', 1, 30000, 30000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5,5, 'order_005', 'product_005', 4, 2500, 10000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);



TRUNCATE ORDER_ITEMS;
INSERT INTO ORDER_ITEMS (ID, ORDERS_ID, PRODUCTS_ID, QUANTITY, PRICE, AMOUNT) 
VALUES ( #{id}, #{ordersId}, #{productsId}, #{quantity}, #{price}, #{amount} )

;


SELECT *
FROM user
WHERE id = 'u1b2c3d4-e5f6-7890-abcd-ef1234567890';